// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/application/accounting/create_transaction_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:home_pocket/features/accounting/domain/models/category.dart'
    as _i7;
import 'package:home_pocket/features/accounting/domain/models/transaction.dart'
    as _i5;
import 'package:home_pocket/features/accounting/domain/repositories/category_repository.dart'
    as _i6;
import 'package:home_pocket/features/accounting/domain/repositories/transaction_repository.dart'
    as _i3;
import 'package:home_pocket/infrastructure/crypto/models/chain_verification_result.dart'
    as _i2;
import 'package:home_pocket/infrastructure/crypto/services/hash_chain_service.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChainVerificationResult_0 extends _i1.SmartFake
    implements _i2.ChainVerificationResult {
  _FakeChainVerificationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i3.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insert(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [transaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Transaction?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i4.Future<_i5.Transaction?>.value(),
          )
          as _i4.Future<_i5.Transaction?>);

  @override
  _i4.Future<List<_i5.Transaction>> findByBookId(
    String? bookId, {
    _i5.LedgerType? ledgerType,
    String? categoryId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #findByBookId,
              [bookId],
              {
                #ledgerType: ledgerType,
                #categoryId: categoryId,
                #startDate: startDate,
                #endDate: endDate,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i4.Future<List<_i5.Transaction>>.value(
              <_i5.Transaction>[],
            ),
          )
          as _i4.Future<List<_i5.Transaction>>);

  @override
  _i4.Future<void> update(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getLatestHash(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestHash, [bookId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<int> countByBookId(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#countByBookId, [bookId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i6.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insert(_i7.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Category?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i4.Future<_i7.Category?>.value(),
          )
          as _i4.Future<_i7.Category?>);

  @override
  _i4.Future<List<_i7.Category>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> findByLevel(int? level) =>
      (super.noSuchMethod(
            Invocation.method(#findByLevel, [level]),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> findByParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#findByParent, [parentId]),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<_i7.Category>> findByType(_i5.TransactionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#findByType, [type]),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<void> insertBatch(List<_i7.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#insertBatch, [categories]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [HashChainService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHashChainService extends _i1.Mock implements _i8.HashChainService {
  MockHashChainService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String calculateTransactionHash({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTransactionHash, [], {
              #transactionId: transactionId,
              #amount: amount,
              #timestamp: timestamp,
              #previousHash: previousHash,
            }),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#calculateTransactionHash, [], {
                #transactionId: transactionId,
                #amount: amount,
                #timestamp: timestamp,
                #previousHash: previousHash,
              }),
            ),
          )
          as String);

  @override
  bool verifyTransactionIntegrity({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
    required String? currentHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTransactionIntegrity, [], {
              #transactionId: transactionId,
              #amount: amount,
              #timestamp: timestamp,
              #previousHash: previousHash,
              #currentHash: currentHash,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i2.ChainVerificationResult verifyChain(
    List<Map<String, dynamic>>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyChain, [transactions]),
            returnValue: _FakeChainVerificationResult_0(
              this,
              Invocation.method(#verifyChain, [transactions]),
            ),
          )
          as _i2.ChainVerificationResult);

  @override
  _i2.ChainVerificationResult verifyChainIncremental(
    List<Map<String, dynamic>>? transactions, {
    required int? lastVerifiedIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyChainIncremental,
              [transactions],
              {#lastVerifiedIndex: lastVerifiedIndex},
            ),
            returnValue: _FakeChainVerificationResult_0(
              this,
              Invocation.method(
                #verifyChainIncremental,
                [transactions],
                {#lastVerifiedIndex: lastVerifiedIndex},
              ),
            ),
          )
          as _i2.ChainVerificationResult);
}
