// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/application/accounting/create_transaction_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:home_pocket/application/dual_ledger/classification_result.dart'
    as _i3;
import 'package:home_pocket/application/dual_ledger/classification_service.dart'
    as _i11;
import 'package:home_pocket/features/accounting/domain/models/category.dart'
    as _i8;
import 'package:home_pocket/features/accounting/domain/models/transaction.dart'
    as _i6;
import 'package:home_pocket/features/accounting/domain/repositories/category_repository.dart'
    as _i7;
import 'package:home_pocket/features/accounting/domain/repositories/transaction_repository.dart'
    as _i4;
import 'package:home_pocket/infrastructure/crypto/models/chain_verification_result.dart'
    as _i2;
import 'package:home_pocket/infrastructure/crypto/services/hash_chain_service.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChainVerificationResult_0 extends _i1.SmartFake
    implements _i2.ChainVerificationResult {
  _FakeChainVerificationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassificationResult_1 extends _i1.SmartFake
    implements _i3.ClassificationResult {
  _FakeClassificationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> insert(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [transaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Transaction?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i5.Future<_i6.Transaction?>.value(),
          )
          as _i5.Future<_i6.Transaction?>);

  @override
  _i5.Future<List<_i6.Transaction>> findByBookId(
    String? bookId, {
    _i6.LedgerType? ledgerType,
    String? categoryId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #findByBookId,
              [bookId],
              {
                #ledgerType: ledgerType,
                #categoryId: categoryId,
                #startDate: startDate,
                #endDate: endDate,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<void> update(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getLatestHash(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestHash, [bookId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<int> countByBookId(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#countByBookId, [bookId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Transaction>> findAllByBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#findAllByBook, [bookId]),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<void> deleteAllByBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllByBook, [bookId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i7.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> insert(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [category]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i8.Category?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i5.Future<_i8.Category?>.value(),
          )
          as _i5.Future<_i8.Category?>);

  @override
  _i5.Future<List<_i8.Category>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);

  @override
  _i5.Future<List<_i8.Category>> findByLevel(int? level) =>
      (super.noSuchMethod(
            Invocation.method(#findByLevel, [level]),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);

  @override
  _i5.Future<List<_i8.Category>> findByParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#findByParent, [parentId]),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);

  @override
  _i5.Future<List<_i8.Category>> findByType(_i6.TransactionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#findByType, [type]),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);

  @override
  _i5.Future<List<_i8.Category>> findWithBudget() =>
      (super.noSuchMethod(
            Invocation.method(#findWithBudget, []),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);

  @override
  _i5.Future<void> insertBatch(List<_i8.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#insertBatch, [categories]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [HashChainService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHashChainService extends _i1.Mock implements _i9.HashChainService {
  MockHashChainService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String calculateTransactionHash({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTransactionHash, [], {
              #transactionId: transactionId,
              #amount: amount,
              #timestamp: timestamp,
              #previousHash: previousHash,
            }),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#calculateTransactionHash, [], {
                #transactionId: transactionId,
                #amount: amount,
                #timestamp: timestamp,
                #previousHash: previousHash,
              }),
            ),
          )
          as String);

  @override
  bool verifyTransactionIntegrity({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
    required String? currentHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTransactionIntegrity, [], {
              #transactionId: transactionId,
              #amount: amount,
              #timestamp: timestamp,
              #previousHash: previousHash,
              #currentHash: currentHash,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i2.ChainVerificationResult verifyChain(
    List<Map<String, dynamic>>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyChain, [transactions]),
            returnValue: _FakeChainVerificationResult_0(
              this,
              Invocation.method(#verifyChain, [transactions]),
            ),
          )
          as _i2.ChainVerificationResult);

  @override
  _i2.ChainVerificationResult verifyChainIncremental(
    List<Map<String, dynamic>>? transactions, {
    required int? lastVerifiedIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyChainIncremental,
              [transactions],
              {#lastVerifiedIndex: lastVerifiedIndex},
            ),
            returnValue: _FakeChainVerificationResult_0(
              this,
              Invocation.method(
                #verifyChainIncremental,
                [transactions],
                {#lastVerifiedIndex: lastVerifiedIndex},
              ),
            ),
          )
          as _i2.ChainVerificationResult);
}

/// A class which mocks [ClassificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationService extends _i1.Mock
    implements _i11.ClassificationService {
  MockClassificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ClassificationResult> classify({
    required String? categoryId,
    String? merchant,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#classify, [], {
              #categoryId: categoryId,
              #merchant: merchant,
              #note: note,
            }),
            returnValue: _i5.Future<_i3.ClassificationResult>.value(
              _FakeClassificationResult_1(
                this,
                Invocation.method(#classify, [], {
                  #categoryId: categoryId,
                  #merchant: merchant,
                  #note: note,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ClassificationResult>);
}
