// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/application/accounting/ensure_default_book_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/features/accounting/domain/models/book.dart' as _i4;
import 'package:home_pocket/features/accounting/domain/repositories/book_repository.dart'
    as _i2;
import 'package:home_pocket/features/accounting/domain/repositories/device_identity_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i2.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i4.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [book]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Book?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i4.Book?>.value(),
          )
          as _i3.Future<_i4.Book?>);

  @override
  _i3.Future<List<_i4.Book>> findAll({bool? includeArchived}) =>
      (super.noSuchMethod(
            Invocation.method(#findAll, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<void> update(_i4.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#update, [book]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> archive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archive, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBalances({
    required String? bookId,
    required int? transactionCount,
    required int? survivalBalance,
    required int? soulBalance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalances, [], {
              #bookId: bookId,
              #transactionCount: transactionCount,
              #survivalBalance: survivalBalance,
              #soulBalance: soulBalance,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DeviceIdentityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceIdentityRepository extends _i1.Mock
    implements _i5.DeviceIdentityRepository {
  MockDeviceIdentityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
