// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/application/accounting/seed_categories_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/features/accounting/domain/models/category.dart'
    as _i4;
import 'package:home_pocket/features/accounting/domain/models/category_ledger_config.dart'
    as _i6;
import 'package:home_pocket/features/accounting/domain/repositories/category_ledger_config_repository.dart'
    as _i5;
import 'package:home_pocket/features/accounting/domain/repositories/category_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i4.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update({
    required String? id,
    String? name,
    String? icon,
    String? color,
    bool? isArchived,
    int? sortOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #name: name,
              #icon: icon,
              #color: color,
              #isArchived: isArchived,
              #sortOrder: sortOrder,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Category?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i4.Category?>.value(),
          )
          as _i3.Future<_i4.Category?>);

  @override
  _i3.Future<List<_i4.Category>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<List<_i4.Category>> findActive() =>
      (super.noSuchMethod(
            Invocation.method(#findActive, []),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<List<_i4.Category>> findByLevel(int? level) =>
      (super.noSuchMethod(
            Invocation.method(#findByLevel, [level]),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<List<_i4.Category>> findByParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#findByParent, [parentId]),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<void> insertBatch(List<_i4.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#insertBatch, [categories]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CategoryLedgerConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryLedgerConfigRepository extends _i1.Mock
    implements _i5.CategoryLedgerConfigRepository {
  MockCategoryLedgerConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsert(_i6.CategoryLedgerConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [config]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.CategoryLedgerConfig?> findById(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [categoryId]),
            returnValue: _i3.Future<_i6.CategoryLedgerConfig?>.value(),
          )
          as _i3.Future<_i6.CategoryLedgerConfig?>);

  @override
  _i3.Future<List<_i6.CategoryLedgerConfig>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i6.CategoryLedgerConfig>>.value(
              <_i6.CategoryLedgerConfig>[],
            ),
          )
          as _i3.Future<List<_i6.CategoryLedgerConfig>>);

  @override
  _i3.Future<void> delete(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [categoryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertBatch(List<_i6.CategoryLedgerConfig>? configs) =>
      (super.noSuchMethod(
            Invocation.method(#upsertBatch, [configs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
