// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/application/ocr/scan_receipt_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i6;

import 'package:home_pocket/infrastructure/ml/image_preprocessor.dart' as _i5;
import 'package:home_pocket/infrastructure/ml/ocr/ocr_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOCRResult_0 extends _i1.SmartFake implements _i2.OCRResult {
  _FakeOCRResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OCRService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOCRService extends _i1.Mock implements _i2.OCRService {
  MockOCRService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.OCRResult> recognizeText(_i4.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeText, [imageFile]),
            returnValue: _i3.Future<_i2.OCRResult>.value(
              _FakeOCRResult_0(
                this,
                Invocation.method(#recognizeText, [imageFile]),
              ),
            ),
          )
          as _i3.Future<_i2.OCRResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImagePreprocessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePreprocessor extends _i1.Mock implements _i5.ImagePreprocessor {
  MockImagePreprocessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Uint8List? processBytes(_i6.Uint8List? input) =>
      (super.noSuchMethod(Invocation.method(#processBytes, [input]))
          as _i6.Uint8List?);
}
