import '../default_merchants.dart';

/// 药妆 (drugstores) → `cat_daily_drugstore`.
/// 百元店 (100-yen shops) / variety → `cat_daily_other`.
/// ホームセンター / 生活用品 (home centers, household goods) →
/// `cat_daily_household`.
const List<DefaultMerchant> dailyDrugstoreMerchants = [
  // ─── ドラッグストア (药妆) → cat_daily_drugstore ───
  DefaultMerchant(
    id: 'mer_matsumoto_kiyoshi',
    nameJa: 'マツモトキヨシ',
    nameZh: '松本清',
    nameEn: 'Matsumoto Kiyoshi',
    aliases: ['マツキヨ', 'Matsukiyo', 'matsumoto kiyoshi', 'matsukiyo'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_welcia',
    nameJa: 'ウエルシア',
    nameEn: 'Welcia',
    aliases: ['Welcia', 'welcia', 'ウェルシア'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_sundrug',
    nameJa: 'サンドラッグ',
    nameEn: 'Sundrug',
    aliases: ['Sundrug', 'sundrug', 'サンドラ'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_tsuruha',
    nameJa: 'ツルハドラッグ',
    nameEn: 'Tsuruha Drug',
    aliases: ['ツルハ', 'Tsuruha', 'tsuruha drug'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_cosmos',
    nameJa: 'コスモス薬品',
    nameEn: 'Cosmos',
    aliases: ['コスモス', 'Cosmos', 'cosmos'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_cocokara_fine',
    nameJa: 'ココカラファイン',
    nameEn: 'Cocokara Fine',
    aliases: ['ココカラ', 'Cocokara Fine', 'cocokara fine'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_kokumin',
    nameJa: 'コクミンドラッグ',
    nameEn: 'Kokumin Drug',
    aliases: ['コクミン', 'Kokumin', 'kokumin drug'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_sugi_drug',
    nameJa: 'スギ薬局',
    nameEn: 'Sugi Pharmacy',
    aliases: ['スギ', 'Sugi', 'sugi pharmacy', 'sugiyakkyoku'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_kirindo',
    nameJa: 'キリン堂',
    nameEn: 'Kirindo',
    aliases: ['Kirindo', 'kirindo'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_create_sd',
    nameJa: 'クリエイトSD',
    nameEn: 'Create SD',
    aliases: ['クリエイト', 'Create SD', 'create sd'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_genky',
    nameJa: 'ゲンキー',
    nameEn: 'Genky',
    aliases: ['Genky', 'genky'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_kusurino_aoki',
    nameJa: 'クスリのアオキ',
    nameEn: 'Kusuri no Aoki',
    aliases: ['アオキ', 'Kusuri no Aoki', 'kusuri no aoki'],
    categoryId: 'cat_daily_drugstore',
  ),
  // ─── 100円ショップ / バラエティ (百元店) → cat_daily_other ───
  DefaultMerchant(
    id: 'mer_daiso',
    nameJa: 'ダイソー',
    nameZh: '大创',
    nameEn: 'Daiso',
    aliases: ['Daiso', 'daiso', 'DAISO', 'ザ・ダイソー'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_seria',
    nameJa: 'セリア',
    nameEn: 'Seria',
    aliases: ['Seria', 'seria'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_can_do',
    nameJa: 'キャンドゥ',
    nameEn: 'Can Do',
    aliases: ['Can Do', 'can do', 'cando', 'キャンドゥー'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_watts',
    nameJa: 'ワッツ',
    nameEn: 'Watts',
    aliases: ['Watts', 'watts'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_don_quijote',
    nameJa: 'ドン・キホーテ',
    nameZh: '唐吉诃德',
    nameEn: 'Don Quijote',
    aliases: ['ドンキ', 'ドンキホーテ', 'Donki', 'don quijote', 'donki', 'MEGAドンキ'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_loft',
    nameJa: 'ロフト',
    nameEn: 'LOFT',
    aliases: ['LOFT', 'loft'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_tokyu_hands',
    nameJa: 'ハンズ',
    nameEn: 'Hands',
    aliases: ['東急ハンズ', 'Tokyu Hands', 'tokyu hands', 'hands'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_plaza',
    nameJa: 'プラザ',
    nameEn: 'PLAZA',
    aliases: ['PLAZA', 'plaza'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_3coins',
    nameJa: 'スリーコインズ',
    nameEn: '3COINS',
    aliases: ['3COINS', '3coins', 'スリコ', 'three coins'],
    categoryId: 'cat_daily_other',
  ),
  // ─── ホームセンター / 生活用品 → cat_daily_household ───
  DefaultMerchant(
    id: 'mer_cainz',
    nameJa: 'カインズ',
    nameEn: 'Cainz',
    aliases: ['Cainz', 'cainz', 'カインズホーム'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_komeri',
    nameJa: 'コメリ',
    nameEn: 'Komeri',
    aliases: ['Komeri', 'komeri'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_kohnan',
    nameJa: 'コーナン',
    nameEn: 'Kohnan',
    aliases: ['Kohnan', 'kohnan', 'コーナン商事'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_dcm',
    nameJa: 'DCM',
    nameEn: 'DCM',
    aliases: ['DCM', 'dcm', 'DCMホーマック', 'DCMカーマ'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_viva_home',
    nameJa: 'ビバホーム',
    nameEn: 'Viva Home',
    aliases: ['Viva Home', 'viva home', 'スーパービバホーム'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_shimachu',
    nameJa: 'シマチュウ',
    nameEn: 'Shimachu',
    aliases: ['島忠', 'Shimachu', 'shimachu', 'シマホ'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_muji',
    nameJa: '無印良品',
    nameZh: '无印良品',
    nameEn: 'MUJI',
    aliases: ['ムジ', 'MUJI', 'muji', 'mujirushi', '無印'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_nitori_deco_home',
    nameJa: 'ニトリデコホーム',
    nameEn: 'Nitori Deco Home',
    aliases: ['デコホーム', 'Deco Home', 'deco home'],
    categoryId: 'cat_daily_household',
  ),
  // ─── 追加: ドラッグストア ───
  DefaultMerchant(
    id: 'mer_v_drug',
    nameJa: 'Vドラッグ',
    nameEn: 'V Drug',
    aliases: ['V Drug', 'v drug', 'ブイドラッグ'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_daikoku_drug',
    nameJa: 'ダイコクドラッグ',
    nameEn: 'Daikoku Drug',
    aliases: ['ダイコク', 'Daikoku Drug', 'daikoku drug'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_sugi_pharmacy_kansai',
    nameJa: 'ドラッグスギ',
    nameEn: 'Drug Sugi',
    aliases: ['Drug Sugi', 'drug sugi'],
    categoryId: 'cat_daily_drugstore',
  ),
  DefaultMerchant(
    id: 'mer_kuko',
    nameJa: 'くすりの福太郎',
    nameEn: 'Fukutaro',
    aliases: ['福太郎', 'Fukutaro', 'fukutaro'],
    categoryId: 'cat_daily_drugstore',
  ),
  // ─── 追加: 100円 / バラエティ ───
  DefaultMerchant(
    id: 'mer_natural_kitchen',
    nameJa: 'ナチュラルキッチン',
    nameEn: 'Natural Kitchen',
    aliases: ['Natural Kitchen', 'natural kitchen', 'ナチュラルキッチン'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_flying_tiger',
    nameJa: 'フライングタイガー',
    nameEn: 'Flying Tiger',
    aliases: ['Flying Tiger', 'flying tiger', 'タイガーコペンハーゲン'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_village_vanguard',
    nameJa: 'ヴィレッジヴァンガード',
    nameEn: 'Village Vanguard',
    aliases: ['ヴィレヴァン', 'Village Vanguard', 'village vanguard'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_itoya',
    nameJa: '伊東屋',
    nameEn: 'Itoya',
    aliases: ['銀座伊東屋', 'Itoya', 'itoya'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_smith',
    nameJa: 'スミス',
    nameEn: 'Smith',
    aliases: ['デルフォニックス', 'Smith', 'smith stationery'],
    categoryId: 'cat_daily_other',
  ),
  DefaultMerchant(
    id: 'mer_sekaido',
    nameJa: '世界堂',
    nameEn: 'Sekaido',
    aliases: ['Sekaido', 'sekaido', 'せかいどう'],
    categoryId: 'cat_daily_other',
  ),
  // ─── 追加: 赤ちゃん用品 → cat_daily_children ───
  DefaultMerchant(
    id: 'mer_akachan_honpo',
    nameJa: 'アカチャンホンポ',
    nameEn: 'Akachan Honpo',
    aliases: ['赤ちゃん本舗', 'Akachan Honpo', 'akachan honpo'],
    categoryId: 'cat_daily_children',
  ),
  DefaultMerchant(
    id: 'mer_babies_r_us',
    nameJa: 'ベビーザらス',
    nameEn: 'Babies R Us',
    aliases: ['Babies R Us', 'babies r us', 'ベビーザらス'],
    categoryId: 'cat_daily_children',
  ),
  DefaultMerchant(
    id: 'mer_nishimatsuya',
    nameJa: '西松屋',
    nameEn: 'Nishimatsuya',
    aliases: ['Nishimatsuya', 'nishimatsuya', 'にしまつや'],
    categoryId: 'cat_daily_children',
  ),
  // ─── 追加: ホームセンター ───
  DefaultMerchant(
    id: 'mer_nafco',
    nameJa: 'ナフコ',
    nameEn: 'Nafco',
    aliases: ['Nafco', 'nafco'],
    categoryId: 'cat_daily_household',
  ),
  DefaultMerchant(
    id: 'mer_keyo_d2',
    nameJa: 'ケーヨーデイツー',
    nameEn: 'Keiyo D2',
    aliases: ['ケーヨー', 'Keiyo D2', 'keiyo d2'],
    categoryId: 'cat_daily_household',
  ),
];
