import '../default_merchants.dart';

/// 超市 (supermarkets) + GMS/discount grocery. Map to `cat_food_groceries`.
/// Pure-GMS general merchandisers (イオン, イトーヨーカドー) also resolve to
/// groceries here — daily-necessities is the dominant basket and keeps the seed
/// unambiguous (recognition refinement is Phase 50's job, not the seed's).
const List<DefaultMerchant> supermarketMerchants = [
  DefaultMerchant(
    id: 'mer_aeon',
    nameJa: 'イオン',
    nameZh: '永旺',
    nameEn: 'AEON',
    aliases: ['AEON', 'aeon', 'イオンモール', 'イオンスタイル', 'aeon mall'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_ito_yokado',
    nameJa: 'イトーヨーカドー',
    nameEn: 'Ito-Yokado',
    aliases: ['ヨーカドー', 'Ito-Yokado', 'ito yokado', 'itoyokado'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_seiyu',
    nameJa: '西友',
    nameEn: 'Seiyu',
    aliases: ['Seiyu', 'seiyu', 'せいゆう'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_life',
    nameJa: 'ライフ',
    nameEn: 'Life',
    aliases: ['Life', 'ライフコーポレーション', 'life supermarket'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_summit',
    nameJa: 'サミット',
    nameEn: 'Summit',
    aliases: ['Summit', 'summit', 'サミットストア'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_maruetsu',
    nameJa: 'マルエツ',
    nameEn: 'Maruetsu',
    aliases: ['Maruetsu', 'maruetsu'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_inageya',
    nameJa: 'いなげや',
    nameEn: 'Inageya',
    aliases: ['Inageya', 'inageya'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_ok_store',
    nameJa: 'オーケー',
    nameEn: 'OK Store',
    aliases: ['オーケーストア', 'OK', 'OKストア', 'ok store'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_gyomu_super',
    nameJa: '業務スーパー',
    nameEn: 'Gyomu Super',
    aliases: ['業スー', 'Gyomu Super', 'gyomu super', 'ぎょうむスーパー'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_gyomu_super_kobe',
    nameJa: '神戸物産',
    nameEn: 'Kobe Bussan',
    aliases: ['Kobe Bussan', 'kobe bussan'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_kasumi',
    nameJa: 'カスミ',
    nameEn: 'Kasumi',
    aliases: ['Kasumi', 'kasumi'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_york_benimaru',
    nameJa: 'ヨークベニマル',
    nameEn: 'York-Benimaru',
    aliases: ['ベニマル', 'York-Benimaru', 'york benimaru'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_heiwado',
    nameJa: '平和堂',
    nameEn: 'Heiwado',
    aliases: ['Heiwado', 'heiwado', 'ヘイワドウ'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_izumiya',
    nameJa: 'イズミヤ',
    nameEn: 'Izumiya',
    aliases: ['Izumiya', 'izumiya'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_hankyu_oasis',
    nameJa: '阪急オアシス',
    nameEn: 'Hankyu Oasis',
    aliases: ['オアシス', 'Hankyu Oasis', 'hankyu oasis'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_seijo_ishii',
    nameJa: '成城石井',
    nameEn: 'Seijo Ishii',
    aliases: ['Seijo Ishii', 'seijo ishii', 'せいじょういしい'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_kaldi',
    nameJa: 'カルディ',
    nameEn: 'KALDI',
    aliases: ['カルディコーヒーファーム', 'KALDI', 'kaldi', 'kaldi coffee farm'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_gyomu_hanamasa',
    nameJa: 'ハナマサ',
    nameEn: 'Hanamasa',
    aliases: ['肉のハナマサ', 'Hanamasa', 'hanamasa'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_costco',
    nameJa: 'コストコ',
    nameZh: '开市客',
    nameEn: 'Costco',
    aliases: ['Costco', 'costco', 'コストコホールセール'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_gyomu_a_price',
    nameJa: 'A-プライス',
    nameEn: 'A-Price',
    aliases: ['A-Price', 'a-price', 'エープライス'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_fuji',
    nameJa: 'フジ',
    nameEn: 'Fuji',
    aliases: ['Fuji', 'フジマート'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_yaoko',
    nameJa: 'ヤオコー',
    nameEn: 'Yaoko',
    aliases: ['Yaoko', 'yaoko'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_belc',
    nameJa: 'ベルク',
    nameEn: 'Belc',
    aliases: ['Belc', 'belc'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_tokyu_store',
    nameJa: '東急ストア',
    nameEn: 'Tokyu Store',
    aliases: ['Tokyu Store', 'tokyu store', 'とうきゅうストア'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_keio_store',
    nameJa: '京王ストア',
    nameEn: 'Keio Store',
    aliases: ['Keio Store', 'keio store'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_odakyu_ox',
    nameJa: 'Odakyu OX',
    nameEn: 'Odakyu OX',
    aliases: ['小田急OX', 'odakyu ox', 'オダキューオーエックス'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_marukyo',
    nameJa: 'マルキョウ',
    nameEn: 'Marukyo',
    aliases: ['Marukyo', 'marukyo'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_sunny',
    nameJa: 'サニー',
    nameEn: 'Sunny',
    aliases: ['Sunny', 'sunny supermarket'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_aeon_max_value',
    nameJa: 'マックスバリュ',
    nameEn: 'MaxValu',
    aliases: ['MaxValu', 'maxvalu', 'マックスバリュー'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_my_basket',
    nameJa: 'まいばすけっと',
    nameEn: 'My Basket',
    aliases: ['My Basket', 'my basket', 'マイバスケット', 'マイバス'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_aeon_big',
    nameJa: 'ザ・ビッグ',
    nameEn: 'The Big',
    aliases: ['ビッグ', 'The Big', 'the big', 'ザビッグ'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_trial',
    nameJa: 'トライアル',
    nameEn: 'Trial',
    aliases: ['Trial', 'trial', 'スーパーセンタートライアル'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_lopia',
    nameJa: 'ロピア',
    nameEn: 'Lopia',
    aliases: ['Lopia', 'lopia'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_gyomu_tokujo',
    nameJa: 'ビッグ・エー',
    nameEn: 'Big-A',
    aliases: ['ビッグエー', 'Big-A', 'big-a'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_aldi',
    nameJa: 'ヨークフーズ',
    nameEn: 'York Foods',
    aliases: ['ヨークフーズ', 'York Foods', 'york foods'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_keisei_store',
    nameJa: 'リブレ京成',
    nameEn: 'Libre Keisei',
    aliases: ['Libre Keisei', 'libre keisei'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_tobu_store',
    nameJa: '東武ストア',
    nameEn: 'Tobu Store',
    aliases: ['Tobu Store', 'tobu store'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_marushoku',
    nameJa: 'マルショク',
    nameEn: 'Marushoku',
    aliases: ['Marushoku', 'marushoku'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_valor',
    nameJa: 'バロー',
    nameEn: 'Valor',
    aliases: ['Valor', 'valor', 'バロー'],
    categoryId: 'cat_food_groceries',
  ),
  DefaultMerchant(
    id: 'mer_apita',
    nameJa: 'アピタ',
    nameEn: 'Apita',
    aliases: ['Apita', 'apita', 'ピアゴ'],
    categoryId: 'cat_food_groceries',
  ),
];
