import '../default_merchants.dart';

/// 書店 (bookstores) → `cat_hobbies_books`.
/// 映画館 (cinemas) → `cat_hobbies_movies`.
/// ゲーム / ホビー → `cat_hobbies_games`.
/// 音楽 / 楽器 → `cat_hobbies_music`.
/// レジャー / アミューズメント → `cat_hobbies_leisure`.
/// ジム (gyms) → `cat_health_fitness`.
/// 旅行代理店 → `cat_hobbies_travel`.
///
/// `cat_hobbies` L1 + its L2s (no overrides) derive to `joy`.
const List<DefaultMerchant> leisureHobbyMerchants = [
  // ─── 書店 → cat_hobbies_books ───
  DefaultMerchant(
    id: 'mer_tsutaya',
    nameJa: 'TSUTAYA',
    nameEn: 'TSUTAYA',
    aliases: ['ツタヤ', 'TSUTAYA', 'tsutaya'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_kinokuniya',
    nameJa: '紀伊國屋書店',
    nameEn: 'Kinokuniya',
    aliases: ['紀伊國屋', 'Kinokuniya', 'kinokuniya', 'きのくにや'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_maruzen',
    nameJa: '丸善',
    nameEn: 'Maruzen',
    aliases: ['Maruzen', 'maruzen', 'まるぜん'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_junkudo',
    nameJa: 'ジュンク堂',
    nameEn: 'Junkudo',
    aliases: ['Junkudo', 'junkudo', 'じゅんくどう'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_book_off',
    nameJa: 'ブックオフ',
    nameEn: 'BOOKOFF',
    aliases: ['BOOKOFF', 'bookoff', 'ブックオフ'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_yurindo',
    nameJa: '有隣堂',
    nameEn: 'Yurindo',
    aliases: ['Yurindo', 'yurindo'],
    categoryId: 'cat_hobbies_books',
  ),
  // ─── 映画館 → cat_hobbies_movies ───
  DefaultMerchant(
    id: 'mer_toho_cinemas',
    nameJa: 'TOHOシネマズ',
    nameEn: 'TOHO Cinemas',
    aliases: ['TOHOシネマズ', 'TOHO Cinemas', 'toho cinemas'],
    categoryId: 'cat_hobbies_movies',
  ),
  DefaultMerchant(
    id: 'mer_united_cinemas',
    nameJa: 'ユナイテッドシネマ',
    nameEn: 'United Cinemas',
    aliases: ['United Cinemas', 'united cinemas'],
    categoryId: 'cat_hobbies_movies',
  ),
  DefaultMerchant(
    id: 'mer_aeon_cinema',
    nameJa: 'イオンシネマ',
    nameEn: 'AEON Cinema',
    aliases: ['イオンシネマ', 'AEON Cinema', 'aeon cinema'],
    categoryId: 'cat_hobbies_movies',
  ),
  DefaultMerchant(
    id: 'mer_109_cinemas',
    nameJa: '109シネマズ',
    nameEn: '109 Cinemas',
    aliases: ['109シネマズ', '109 cinemas'],
    categoryId: 'cat_hobbies_movies',
  ),
  // ─── ゲーム / ホビー → cat_hobbies_games ───
  DefaultMerchant(
    id: 'mer_game_tsutaya',
    nameJa: 'ゲオ',
    nameEn: 'GEO',
    aliases: ['GEO', 'geo', 'ゲオ'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_yodobashi_game',
    nameJa: 'スーパーポテト',
    nameEn: 'Super Potato',
    aliases: ['Super Potato', 'super potato', 'スーパーポテト'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_animate',
    nameJa: 'アニメイト',
    nameEn: 'animate',
    aliases: ['animate', 'アニメイト'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_yellow_submarine',
    nameJa: 'イエローサブマリン',
    nameEn: 'Yellow Submarine',
    aliases: ['Yellow Submarine', 'yellow submarine'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_nintendo_store',
    nameJa: 'Nintendo TOKYO',
    nameEn: 'Nintendo TOKYO',
    aliases: ['任天堂', 'Nintendo', 'nintendo tokyo'],
    categoryId: 'cat_hobbies_games',
  ),
  // ─── 音楽 / 楽器 → cat_hobbies_music ───
  DefaultMerchant(
    id: 'mer_tower_records',
    nameJa: 'タワーレコード',
    nameEn: 'TOWER RECORDS',
    aliases: ['タワレコ', 'Tower Records', 'tower records'],
    categoryId: 'cat_hobbies_music',
  ),
  DefaultMerchant(
    id: 'mer_shimamura_gakki',
    nameJa: '島村楽器',
    nameEn: 'Shimamura Gakki',
    aliases: ['島村楽器', 'Shimamura Gakki', 'shimamura gakki'],
    categoryId: 'cat_hobbies_music',
  ),
  DefaultMerchant(
    id: 'mer_yamaha_music',
    nameJa: 'ヤマハミュージック',
    nameEn: 'Yamaha Music',
    aliases: ['ヤマハ', 'Yamaha Music', 'yamaha music'],
    categoryId: 'cat_hobbies_music',
  ),
  // ─── レジャー / アミューズメント → cat_hobbies_leisure ───
  DefaultMerchant(
    id: 'mer_round1',
    nameJa: 'ラウンドワン',
    nameEn: 'Round1',
    aliases: ['ラウワン', 'Round1', 'round1', 'round one'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_namco',
    nameJa: 'ナムコ',
    nameEn: 'namco',
    aliases: ['namco', 'ナムコ'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_taito_station',
    nameJa: 'タイトーステーション',
    nameEn: 'Taito Station',
    aliases: ['タイトー', 'Taito', 'taito station'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_karaoke_kan',
    nameJa: 'カラオケ館',
    nameEn: 'Karaoke Kan',
    aliases: ['Karaoke Kan', 'karaoke kan', 'カラオケかん'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_big_echo',
    nameJa: 'ビッグエコー',
    nameEn: 'BIG ECHO',
    aliases: ['BIG ECHO', 'big echo', 'ビッグエコー'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_joysound',
    nameJa: 'カラオケJOYSOUND',
    nameEn: 'JOYSOUND',
    aliases: ['JOYSOUND', 'joysound', 'ジョイサウンド'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_disney',
    nameJa: '東京ディズニーリゾート',
    nameZh: '东京迪士尼',
    nameEn: 'Tokyo Disney Resort',
    aliases: ['ディズニー', 'TDR', 'Disney', 'disney', 'tokyo disney'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_usj',
    nameJa: 'ユニバーサルスタジオジャパン',
    nameZh: '日本环球影城',
    nameEn: 'USJ',
    aliases: ['USJ', 'usj', 'ユニバ', 'universal studios japan'],
    categoryId: 'cat_hobbies_leisure',
  ),
  // ─── ジム → cat_health_fitness ───
  DefaultMerchant(
    id: 'mer_anytime_fitness',
    nameJa: 'エニタイムフィットネス',
    nameEn: 'Anytime Fitness',
    aliases: ['エニタイム', 'Anytime Fitness', 'anytime fitness'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_konami_sports',
    nameJa: 'コナミスポーツ',
    nameEn: 'Konami Sports',
    aliases: ['Konami Sports', 'konami sports', 'コナミスポーツクラブ'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_central_sports',
    nameJa: 'セントラルスポーツ',
    nameEn: 'Central Sports',
    aliases: ['Central Sports', 'central sports'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_chocozap',
    nameJa: 'チョコザップ',
    nameEn: 'chocoZAP',
    aliases: ['chocoZAP', 'chocozap', 'チョコザップ'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_renaissance',
    nameJa: 'ルネサンス',
    nameEn: 'Renaissance',
    aliases: ['Renaissance', 'renaissance', 'スポーツクラブルネサンス'],
    categoryId: 'cat_health_fitness',
  ),
  // ─── スポーツ用品 → cat_hobbies_leisure ───
  DefaultMerchant(
    id: 'mer_xebio',
    nameJa: 'ゼビオ',
    nameEn: 'Xebio',
    aliases: ['Xebio', 'xebio', 'スーパースポーツゼビオ'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_alpen',
    nameJa: 'アルペン',
    nameEn: 'Alpen',
    aliases: ['Alpen', 'alpen', 'スポーツデポ'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_kojitusanso',
    nameJa: '好日山荘',
    nameEn: 'Kojitusanso',
    aliases: ['Kojitusanso', 'kojitusanso'],
    categoryId: 'cat_hobbies_leisure',
  ),
  // ─── 旅行代理店 → cat_hobbies_travel ───
  DefaultMerchant(
    id: 'mer_jtb',
    nameJa: 'JTB',
    nameEn: 'JTB',
    aliases: ['JTB', 'jtb'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_his',
    nameJa: 'エイチアイエス',
    nameEn: 'H.I.S.',
    aliases: ['HIS', 'his', 'H.I.S.', 'エイチ・アイ・エス'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_rakuten_travel',
    nameJa: '楽天トラベル',
    nameEn: 'Rakuten Travel',
    aliases: ['Rakuten Travel', 'rakuten travel', '楽天トラベル'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_jalan',
    nameJa: 'じゃらん',
    nameEn: 'Jalan',
    aliases: ['Jalan', 'jalan', 'じゃらんnet'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_ikyu',
    nameJa: '一休',
    nameEn: 'Ikyu',
    aliases: ['一休.com', 'Ikyu', 'ikyu'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_booking_com',
    nameJa: 'Booking.com',
    nameEn: 'Booking.com',
    aliases: ['ブッキング', 'booking.com', 'booking'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_apa_hotel',
    nameJa: 'アパホテル',
    nameEn: 'APA Hotel',
    aliases: ['アパ', 'APA Hotel', 'apa hotel'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_toyoko_inn',
    nameJa: '東横イン',
    nameEn: 'Toyoko Inn',
    aliases: ['東横INN', 'Toyoko Inn', 'toyoko inn'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_dormy_inn',
    nameJa: 'ドーミーイン',
    nameEn: 'Dormy Inn',
    aliases: ['Dormy Inn', 'dormy inn', 'ドーミーイン'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_super_hotel',
    nameJa: 'スーパーホテル',
    nameEn: 'Super Hotel',
    aliases: ['Super Hotel', 'super hotel', 'スーパーホテル'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_route_inn',
    nameJa: 'ルートイン',
    nameEn: 'Route Inn',
    aliases: ['Route Inn', 'route inn', 'ホテルルートイン'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_agoda',
    nameJa: 'アゴダ',
    nameEn: 'Agoda',
    aliases: ['Agoda', 'agoda'],
    categoryId: 'cat_hobbies_travel',
  ),
  DefaultMerchant(
    id: 'mer_expedia',
    nameJa: 'エクスペディア',
    nameEn: 'Expedia',
    aliases: ['Expedia', 'expedia'],
    categoryId: 'cat_hobbies_travel',
  ),
  // ─── 追加: 書店 / ホビー ───
  DefaultMerchant(
    id: 'mer_yodobashi_books',
    nameJa: '三省堂書店',
    nameEn: 'Sanseido',
    aliases: ['三省堂', 'Sanseido', 'sanseido'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_books_kinokuniya',
    nameJa: '未来屋書店',
    nameEn: 'Miraiya Shoten',
    aliases: ['未来屋', 'Miraiya', 'miraiya shoten'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_villevan_books',
    nameJa: '文教堂',
    nameEn: 'Bunkyodo',
    aliases: ['Bunkyodo', 'bunkyodo', 'ぶんきょうどう'],
    categoryId: 'cat_hobbies_books',
  ),
  DefaultMerchant(
    id: 'mer_mandarake',
    nameJa: 'まんだらけ',
    nameEn: 'Mandarake',
    aliases: ['Mandarake', 'mandarake', 'まんだらけ'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_surugaya',
    nameJa: '駿河屋',
    nameEn: 'Surugaya',
    aliases: ['Surugaya', 'surugaya', 'するがや'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_kid_land',
    nameJa: 'キデイランド',
    nameEn: 'KIDDY LAND',
    aliases: ['KIDDY LAND', 'kiddy land', 'キデイランド'],
    categoryId: 'cat_hobbies_games',
  ),
  DefaultMerchant(
    id: 'mer_tokyu_hands_hobby',
    nameJa: 'ヨドバシホビー',
    nameEn: 'Hobby Off',
    aliases: ['ホビーオフ', 'Hobby Off', 'hobby off'],
    categoryId: 'cat_hobbies_games',
  ),
  // ─── 追加: ジム ───
  DefaultMerchant(
    id: 'mer_gold_gym',
    nameJa: 'ゴールドジム',
    nameEn: "GOLD'S GYM",
    aliases: ["GOLD'S GYM", 'golds gym', 'ゴールドジム'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_tipness',
    nameJa: 'ティップネス',
    nameEn: 'Tipness',
    aliases: ['Tipness', 'tipness', 'ティップネス'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_curves',
    nameJa: 'カーブス',
    nameEn: 'Curves',
    aliases: ['Curves', 'curves', 'カーブス'],
    categoryId: 'cat_health_fitness',
  ),
  DefaultMerchant(
    id: 'mer_lava',
    nameJa: 'LAVA',
    nameEn: 'LAVA',
    aliases: ['ホットヨガLAVA', 'LAVA', 'lava'],
    categoryId: 'cat_health_fitness',
  ),
  // ─── 追加: レジャー ───
  DefaultMerchant(
    id: 'mer_aquarium_sunshine',
    nameJa: 'サンシャイン水族館',
    nameEn: 'Sunshine Aquarium',
    aliases: ['Sunshine Aquarium', 'sunshine aquarium'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_spa_world',
    nameJa: 'スパワールド',
    nameEn: 'Spa World',
    aliases: ['Spa World', 'spa world', 'スパワールド'],
    categoryId: 'cat_hobbies_leisure',
  ),
  DefaultMerchant(
    id: 'mer_super_sento',
    nameJa: '極楽湯',
    nameEn: 'Gokurakuyu',
    aliases: ['極楽湯', 'Gokurakuyu', 'gokurakuyu'],
    categoryId: 'cat_hobbies_leisure',
  ),
];
