import '../default_merchants.dart';

/// 咖啡 / カフェ. Map to `cat_food_cafe`.
const List<DefaultMerchant> cafeMerchants = [
  DefaultMerchant(
    id: 'mer_starbucks',
    nameJa: 'スターバックス',
    nameZh: '星巴克',
    nameEn: 'Starbucks',
    aliases: ['スタバ', 'Starbucks', 'starbucks', 'starbucks coffee'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_doutor',
    nameJa: 'ドトール',
    nameEn: 'Doutor',
    aliases: ['Doutor', 'doutor', 'ドトールコーヒー', 'どとーる'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_tullys',
    nameJa: 'タリーズ',
    nameEn: "Tully's Coffee",
    aliases: ['Tullys', 'tullys', "tully's", 'タリーズコーヒー'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_excelsior',
    nameJa: 'エクセルシオール',
    nameEn: 'Excelsior Caffe',
    aliases: ['Excelsior', 'excelsior', 'エクセルシオールカフェ'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_komeda',
    nameJa: 'コメダ珈琲店',
    nameEn: 'Komeda Coffee',
    aliases: ['コメダ', 'Komeda', 'komeda', 'komeda coffee', 'こめだ'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_pronto',
    nameJa: 'プロント',
    nameEn: 'Pronto',
    aliases: ['Pronto', 'pronto'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_veloce',
    nameJa: 'ベローチェ',
    nameEn: 'Caffe Veloce',
    aliases: ['カフェベローチェ', 'Veloce', 'veloce'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_saint_marc',
    nameJa: 'サンマルクカフェ',
    nameEn: 'Saint Marc Cafe',
    aliases: ['サンマルク', 'Saint Marc', 'saint marc cafe'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_ueshima',
    nameJa: '上島珈琲店',
    nameEn: 'Ueshima Coffee',
    aliases: ['上島珈琲', 'UCC', 'Ueshima', 'ueshima coffee'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_hoshino_coffee',
    nameJa: '星乃珈琲店',
    nameEn: 'Hoshino Coffee',
    aliases: ['星乃珈琲', 'Hoshino Coffee', 'hoshino coffee'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_cafe_renoir',
    nameJa: '喫茶室ルノアール',
    nameEn: 'Cafe Renoir',
    aliases: ['ルノアール', 'Renoir', 'renoir', 'cafe renoir'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_blue_bottle',
    nameJa: 'ブルーボトルコーヒー',
    nameEn: 'Blue Bottle Coffee',
    aliases: ['ブルーボトル', 'Blue Bottle', 'blue bottle coffee'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_gong_cha',
    nameJa: 'ゴンチャ',
    nameZh: '贡茶',
    nameEn: 'Gong cha',
    aliases: ['Gong cha', 'gong cha', 'gongcha'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_the_alley',
    nameJa: 'ジ アレイ',
    nameEn: 'The Alley',
    aliases: ['The Alley', 'the alley', 'アレイ'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_cocos_cafe',
    nameJa: 'カフェ・ド・クリエ',
    nameEn: 'Cafe de Crie',
    aliases: ['ドクリエ', 'Cafe de Crie', 'cafe de crie'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_segafredo',
    nameJa: 'セガフレード',
    nameEn: 'Segafredo',
    aliases: ['Segafredo', 'segafredo', 'セガフレード・ザネッティ'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_chao_bamboo',
    nameJa: 'チャオプレッソ',
    nameEn: 'Ciao Presso',
    aliases: ['Ciao Presso', 'ciao presso'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_machi_cafe',
    nameJa: 'マチカフェ',
    nameEn: 'Machi Cafe',
    aliases: ['Machi Cafe', 'machi cafe', 'マチカフェ'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_tapioca_koi',
    nameJa: 'コイティー',
    nameEn: 'KOI Thé',
    aliases: ['KOI', 'koi the', 'コイティー'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_chatime',
    nameJa: 'チャタイム',
    nameEn: 'Chatime',
    aliases: ['Chatime', 'chatime'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_kissa_ten',
    nameJa: '珈琲館',
    nameEn: 'Coffeekan',
    aliases: ['珈琲館', 'Coffeekan', 'coffeekan'],
    categoryId: 'cat_food_cafe',
  ),
  DefaultMerchant(
    id: 'mer_caffe_solare',
    nameJa: 'カフェ・ソラーレ',
    nameEn: 'Caffe Solare',
    aliases: ['Solare', 'solare', 'カフェソラーレ'],
    categoryId: 'cat_food_cafe',
  ),
];
