import '../default_merchants.dart';

/// 外食 (eating out): 牛丼 / ラーメン / ファストフード / ファミレス / 回転寿司 /
/// 焼肉 / カレー / 定食. Map to `cat_food_dining_out`. 居酒屋 (izakaya) map to
/// `cat_food_drinks` — alcohol-led spend.
const List<DefaultMerchant> diningMerchants = [
  // ─── ファストフード ───
  DefaultMerchant(
    id: 'mer_mcdonalds',
    nameJa: 'マクドナルド',
    nameZh: '麦当劳',
    nameEn: "McDonald's",
    aliases: ['マック', 'マクド', 'Mac', 'McDonald', 'mcdonalds', 'マクドナルド'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_mos_burger',
    nameJa: 'モスバーガー',
    nameEn: 'MOS Burger',
    aliases: ['モス', 'MOS', 'mos burger', 'mosburger'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kfc',
    nameJa: 'ケンタッキー',
    nameZh: '肯德基',
    nameEn: 'KFC',
    aliases: ['ケンタ', 'KFC', 'kfc', 'ケンタッキーフライドチキン', 'kentucky'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_lotteria',
    nameJa: 'ロッテリア',
    nameEn: 'Lotteria',
    aliases: ['Lotteria', 'lotteria'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_freshness_burger',
    nameJa: 'フレッシュネスバーガー',
    nameEn: 'Freshness Burger',
    aliases: ['フレッシュネス', 'Freshness Burger', 'freshness burger'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_burger_king',
    nameJa: 'バーガーキング',
    nameZh: '汉堡王',
    nameEn: 'Burger King',
    aliases: ['バーキン', 'Burger King', 'burger king', 'burgerking'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_subway',
    nameJa: 'サブウェイ',
    nameZh: '赛百味',
    nameEn: 'Subway',
    aliases: ['Subway', 'subway'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 牛丼 ───
  DefaultMerchant(
    id: 'mer_yoshinoya',
    nameJa: '吉野家',
    nameEn: 'Yoshinoya',
    aliases: ['Yoshinoya', 'yoshinoya', 'よしのや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_sukiya',
    nameJa: 'すき家',
    nameEn: 'Sukiya',
    aliases: ['Sukiya', 'sukiya', 'すきや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_matsuya',
    nameJa: '松屋',
    nameEn: 'Matsuya',
    aliases: ['Matsuya', 'matsuya', 'まつや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_nakau',
    nameJa: 'なか卯',
    nameEn: 'Nakau',
    aliases: ['Nakau', 'nakau', 'なかう'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── ラーメン ───
  DefaultMerchant(
    id: 'mer_ichiran',
    nameJa: '一蘭',
    nameZh: '一兰拉面',
    nameEn: 'Ichiran',
    aliases: ['Ichiran', 'ichiran', 'いちらん'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_ippudo',
    nameJa: '一風堂',
    nameEn: 'Ippudo',
    aliases: ['Ippudo', 'ippudo', 'いっぷうどう'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_tenkaippin',
    nameJa: '天下一品',
    nameEn: 'Tenkaippin',
    aliases: ['天一', 'Tenkaippin', 'tenkaippin', 'てんかいっぴん'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_hidakaya',
    nameJa: '日高屋',
    nameEn: 'Hidakaya',
    aliases: ['Hidakaya', 'hidakaya', 'ひだかや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_korakuen',
    nameJa: '幸楽苑',
    nameEn: 'Korakuen',
    aliases: ['Korakuen', 'korakuen'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_ringer_hut',
    nameJa: 'リンガーハット',
    nameEn: 'Ringer Hut',
    aliases: ['リンガー', 'Ringer Hut', 'ringer hut'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_8ban_ramen',
    nameJa: '8番らーめん',
    nameEn: 'Hachiban Ramen',
    aliases: ['8番', 'Hachiban', 'hachiban ramen'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 中華 / 餃子 ───
  DefaultMerchant(
    id: 'mer_gyoza_ohsho',
    nameJa: '餃子の王将',
    nameEn: 'Gyoza no Ohsho',
    aliases: ['王将', 'Ohsho', 'gyoza no ohsho', 'ぎょうざのおうしょう'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_osaka_ohsho',
    nameJa: '大阪王将',
    nameEn: 'Osaka Ohsho',
    aliases: ['Osaka Ohsho', 'osaka ohsho'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_bamiyan',
    nameJa: 'バーミヤン',
    nameEn: 'Bamiyan',
    aliases: ['Bamiyan', 'bamiyan'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 回転寿司 ───
  DefaultMerchant(
    id: 'mer_sushiro',
    nameJa: 'スシロー',
    nameZh: '寿司郎',
    nameEn: 'Sushiro',
    aliases: ['Sushiro', 'sushiro', 'すしろー'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kura_sushi',
    nameJa: 'くら寿司',
    nameEn: 'Kura Sushi',
    aliases: ['くら', 'Kura Sushi', 'kura sushi', 'くらずし'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_hama_sushi',
    nameJa: 'はま寿司',
    nameEn: 'Hama Sushi',
    aliases: ['Hama Sushi', 'hama sushi', 'はまずし'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kappa_sushi',
    nameJa: 'かっぱ寿司',
    nameEn: 'Kappa Sushi',
    aliases: ['Kappa Sushi', 'kappa sushi', 'かっぱずし'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── ファミレス ───
  DefaultMerchant(
    id: 'mer_gusto',
    nameJa: 'ガスト',
    nameEn: 'Gusto',
    aliases: ['Gusto', 'gusto', 'がすと'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_saizeriya',
    nameJa: 'サイゼリヤ',
    nameZh: '萨莉亚',
    nameEn: 'Saizeriya',
    aliases: ['サイゼ', 'Saizeriya', 'saizeriya', 'さいぜりや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_jonathans',
    nameJa: 'ジョナサン',
    nameEn: "Jonathan's",
    aliases: ['Jonathan', 'jonathans', 'ジョナサンズ'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_royal_host',
    nameJa: 'ロイヤルホスト',
    nameEn: 'Royal Host',
    aliases: ['ロイホ', 'Royal Host', 'royal host'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_dennys',
    nameJa: 'デニーズ',
    nameEn: "Denny's",
    aliases: ['Denny', 'dennys', "denny's"],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_cocos',
    nameJa: 'ココス',
    nameEn: "COCO'S",
    aliases: ['COCOS', 'cocos', "coco's"],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_joyfull',
    nameJa: 'ジョイフル',
    nameEn: 'Joyfull',
    aliases: ['Joyfull', 'joyfull'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── カレー ───
  DefaultMerchant(
    id: 'mer_coco_ichibanya',
    nameJa: 'ココイチ',
    nameEn: 'CoCo Ichibanya',
    aliases: ['カレーハウスCoCo壱番屋', 'CoCo壱', 'coco ichibanya', 'cocoichi'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_go_go_curry',
    nameJa: 'ゴーゴーカレー',
    nameEn: 'Go Go Curry',
    aliases: ['Go Go Curry', 'go go curry', 'ゴーゴー'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 定食 / 和食 ───
  DefaultMerchant(
    id: 'mer_ootoya',
    nameJa: '大戸屋',
    nameEn: 'Ootoya',
    aliases: ['Ootoya', 'ootoya', 'おおとや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_yayoiken',
    nameJa: 'やよい軒',
    nameEn: 'Yayoiken',
    aliases: ['Yayoiken', 'yayoiken', 'やよいけん'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_tenya',
    nameJa: 'てんや',
    nameEn: 'Tenya',
    aliases: ['天丼てんや', 'Tenya', 'tenya'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_marugame_seimen',
    nameJa: '丸亀製麺',
    nameEn: 'Marugame Seimen',
    aliases: ['丸亀', 'Marugame', 'marugame seimen', 'まるがめせいめん'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_hanamaru_udon',
    nameJa: 'はなまるうどん',
    nameEn: 'Hanamaru Udon',
    aliases: ['はなまる', 'Hanamaru Udon', 'hanamaru udon'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_fuji_soba',
    nameJa: '富士そば',
    nameEn: 'Fuji Soba',
    aliases: ['名代富士そば', 'Fuji Soba', 'fuji soba'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 焼肉 / 寿司居酒屋 / ステーキ ───
  DefaultMerchant(
    id: 'mer_gyukaku',
    nameJa: '牛角',
    nameEn: 'Gyukaku',
    aliases: ['Gyukaku', 'gyukaku', 'ぎゅうかく'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_yakiniku_like',
    nameJa: '焼肉ライク',
    nameEn: 'Yakiniku Like',
    aliases: ['Yakiniku Like', 'yakiniku like'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_ikinari_steak',
    nameJa: 'いきなりステーキ',
    nameEn: 'Ikinari Steak',
    aliases: ['Ikinari Steak', 'ikinari steak'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_pepper_lunch',
    nameJa: 'ペッパーランチ',
    nameEn: 'Pepper Lunch',
    aliases: ['Pepper Lunch', 'pepper lunch'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kushikatsu_tanaka',
    nameJa: '串カツ田中',
    nameEn: 'Kushikatsu Tanaka',
    aliases: ['Kushikatsu Tanaka', 'kushikatsu tanaka', 'くしかつたなか'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── お好み焼き / うどん / その他 ───
  DefaultMerchant(
    id: 'mer_ootafuku',
    nameJa: '築地銀だこ',
    nameEn: 'Gindaco',
    aliases: ['銀だこ', 'Gindaco', 'gindaco', 'ぎんだこ'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_mister_donut',
    nameJa: 'ミスタードーナツ',
    nameEn: 'Mister Donut',
    aliases: ['ミスド', 'Mister Donut', 'mister donut', 'misdo'],
    categoryId: 'cat_food_dining_out',
  ),
  // ─── 居酒屋 (alcohol-led → drinks) ───
  DefaultMerchant(
    id: 'mer_torikizoku',
    nameJa: '鳥貴族',
    nameEn: 'Torikizoku',
    aliases: ['トリキ', 'Torikizoku', 'torikizoku', 'とりきぞく'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_watami',
    nameJa: 'ワタミ',
    nameEn: 'Watami',
    aliases: ['Watami', 'watami', 'わたみ'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_shirokiya',
    nameJa: '白木屋',
    nameEn: 'Shirokiya',
    aliases: ['Shirokiya', 'shirokiya'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_kin_no_kura',
    nameJa: '金の蔵',
    nameEn: 'Kin no Kura',
    aliases: ['Kin no Kura', 'kin no kura'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_yakitori_isomaru',
    nameJa: '磯丸水産',
    nameEn: 'Isomaru Suisan',
    aliases: ['磯丸', 'Isomaru', 'isomaru suisan'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_kushikatsu_dengana',
    nameJa: '養老乃瀧',
    nameEn: 'Yoro no Taki',
    aliases: ['養老の瀧', 'Yoro no Taki', 'yoro no taki'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_uotami',
    nameJa: '魚民',
    nameEn: 'Uotami',
    aliases: ['Uotami', 'uotami', 'うおたみ'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_warawara',
    nameJa: '笑笑',
    nameEn: 'Warawara',
    aliases: ['Warawara', 'warawara', 'わらわら'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_kushikatsu_tokugawa',
    nameJa: 'てけてけ',
    nameEn: 'Teketeke',
    aliases: ['Teketeke', 'teketeke'],
    categoryId: 'cat_food_drinks',
  ),
  DefaultMerchant(
    id: 'mer_hub',
    nameJa: 'HUB',
    nameEn: 'HUB',
    aliases: ['英国パブHUB', 'HUB', 'hub pub'],
    categoryId: 'cat_food_drinks',
  ),
  // ─── 追加: ファストフード / カフェ飯 / その他 ───
  DefaultMerchant(
    id: 'mer_first_kitchen',
    nameJa: 'ファーストキッチン',
    nameEn: 'First Kitchen',
    aliases: ['ファッキン', 'First Kitchen', 'first kitchen', 'ウェンディーズ・ファーストキッチン'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_a_and_w',
    nameJa: 'A&W',
    nameEn: 'A&W',
    aliases: ['エイアンドダブリュ', 'a&w', 'aw'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kourakuen_chinese',
    nameJa: 'バーミヤン餃子',
    nameEn: 'Bamiyan Gyoza',
    aliases: ['Bamiyan Gyoza', 'bamiyan gyoza'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kacchan',
    nameJa: 'かつや',
    nameEn: 'Katsuya',
    aliases: ['Katsuya', 'katsuya', 'かつや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_matsunoya',
    nameJa: 'まつのや',
    nameEn: 'Matsunoya',
    aliases: ['松のや', 'Matsunoya', 'matsunoya'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_tonkatsu_wako',
    nameJa: 'とんかつ和幸',
    nameEn: 'Tonkatsu Wako',
    aliases: ['和幸', 'Wako', 'tonkatsu wako'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_ootoya_teishoku',
    nameJa: '宮本むなし',
    nameEn: 'Miyamoto Munashi',
    aliases: ['めしや宮本むなし', 'Miyamoto Munashi', 'miyamoto munashi'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_tomato_no_ki',
    nameJa: 'サイゼ系イタリアン',
    nameEn: 'Capricciosa',
    aliases: ['カプリチョーザ', 'Capricciosa', 'capricciosa'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_kfc_chicken',
    nameJa: 'クリスピー・クリーム・ドーナツ',
    nameEn: 'Krispy Kreme',
    aliases: ['クリスピークリーム', 'Krispy Kreme', 'krispy kreme'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_baskin_robbins',
    nameJa: 'サーティワン',
    nameEn: 'Baskin-Robbins',
    aliases: ['31', 'サーティワンアイスクリーム', 'Baskin Robbins', 'baskin-robbins'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_cold_stone',
    nameJa: 'コールドストーン',
    nameEn: 'Cold Stone Creamery',
    aliases: ['Cold Stone', 'cold stone', 'コールドストーンクリーマリー'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_chateraise',
    nameJa: 'シャトレーゼ',
    nameEn: 'Chateraise',
    aliases: ['Chateraise', 'chateraise', 'シャトレーゼ'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_fujiya',
    nameJa: '不二家',
    nameEn: 'Fujiya',
    aliases: ['Fujiya', 'fujiya', 'ふじや'],
    categoryId: 'cat_food_dining_out',
  ),
  DefaultMerchant(
    id: 'mer_st_etoile',
    nameJa: 'シャトレーゼカフェ',
    nameEn: 'Yatsudoki',
    aliases: ['YATSUDOKI', 'yatsudoki'],
    categoryId: 'cat_food_dining_out',
  ),
];
