// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/features/security/data/database/encrypted_database_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cryptography/cryptography.dart' as _i3;
import 'package:home_pocket/features/security/application/services/key_manager.dart'
    as _i4;
import 'package:home_pocket/features/security/domain/models/device_key_pair.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceKeyPair_0 extends _i1.SmartFake implements _i2.DeviceKeyPair {
  _FakeDeviceKeyPair_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignature_1 extends _i1.SmartFake implements _i3.Signature {
  _FakeSignature_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyManager extends _i1.Mock implements _i4.KeyManager {
  MockKeyManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DeviceKeyPair> generateDeviceKeyPair() => (super.noSuchMethod(
        Invocation.method(
          #generateDeviceKeyPair,
          [],
        ),
        returnValue: _i5.Future<_i2.DeviceKeyPair>.value(_FakeDeviceKeyPair_0(
          this,
          Invocation.method(
            #generateDeviceKeyPair,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DeviceKeyPair>);

  @override
  _i5.Future<String?> getPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getPublicKey,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getDeviceId() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasKeyPair() => (super.noSuchMethod(
        Invocation.method(
          #hasKeyPair,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Signature> signData(List<int>? data) => (super.noSuchMethod(
        Invocation.method(
          #signData,
          [data],
        ),
        returnValue: _i5.Future<_i3.Signature>.value(_FakeSignature_1(
          this,
          Invocation.method(
            #signData,
            [data],
          ),
        )),
      ) as _i5.Future<_i3.Signature>);

  @override
  _i5.Future<bool> verifySignature({
    required List<int>? data,
    required _i3.Signature? signature,
    required String? publicKeyBase64,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifySignature,
          [],
          {
            #data: data,
            #signature: signature,
            #publicKeyBase64: publicKeyBase64,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.DeviceKeyPair> recoverFromSeed(List<int>? seed) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverFromSeed,
          [seed],
        ),
        returnValue: _i5.Future<_i2.DeviceKeyPair>.value(_FakeDeviceKeyPair_0(
          this,
          Invocation.method(
            #recoverFromSeed,
            [seed],
          ),
        )),
      ) as _i5.Future<_i2.DeviceKeyPair>);
}
