targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*.dart

      freezed:
        generate_for:
          - lib/**/*.dart

      json_serializable:
        generate_for:
          - lib/**/*.dart
        options:
          # JSON serialization options
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

      # drift_dev: Use default configuration (generates for all lib/**/*.dart)
      # Explicit configuration was preventing generation
