// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/features/home/presentation/providers/today_transactions_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/features/accounting/domain/models/transaction.dart'
    as _i4;
import 'package:home_pocket/features/accounting/domain/repositories/transaction_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Transaction?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i4.Transaction?>.value(),
          )
          as _i3.Future<_i4.Transaction?>);

  @override
  _i3.Future<List<_i4.Transaction>> findByBookId(
    String? bookId, {
    _i4.LedgerType? ledgerType,
    String? categoryId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #findByBookId,
              [bookId],
              {
                #ledgerType: ledgerType,
                #categoryId: categoryId,
                #startDate: startDate,
                #endDate: endDate,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> update(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getLatestHash(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestHash, [bookId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int> countByBookId(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#countByBookId, [bookId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Transaction>> findAllByBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#findAllByBook, [bookId]),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> deleteAllByBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllByBook, [bookId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
