// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/integration/sync/bill_sync_round_trip_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/features/family_sync/domain/models/group_info.dart'
    as _i7;
import 'package:home_pocket/features/family_sync/domain/models/group_member.dart'
    as _i6;
import 'package:home_pocket/features/family_sync/domain/repositories/group_repository.dart'
    as _i5;
import 'package:home_pocket/infrastructure/crypto/services/field_encryption_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FieldEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFieldEncryptionService extends _i1.Mock
    implements _i2.FieldEncryptionService {
  MockFieldEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> encryptField(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encryptField, [plaintext]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encryptField, [plaintext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> decryptField(String? ciphertext) =>
      (super.noSuchMethod(
            Invocation.method(#decryptField, [ciphertext]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decryptField, [ciphertext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> encryptAmount(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#encryptAmount, [amount]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encryptAmount, [amount]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<double> decryptAmount(String? encrypted) =>
      (super.noSuchMethod(
            Invocation.method(#decryptAmount, [encrypted]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i5.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePendingGroup({
    required String? groupId,
    required String? groupName,
    required String? inviteCode,
    required DateTime? inviteExpiresAt,
    required String? groupKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePendingGroup, [], {
              #groupId: groupId,
              #groupName: groupName,
              #inviteCode: inviteCode,
              #inviteExpiresAt: inviteExpiresAt,
              #groupKey: groupKey,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveConfirmingGroup({
    required String? groupId,
    required String? groupName,
    required List<_i6.GroupMember>? members,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfirmingGroup, [], {
              #groupId: groupId,
              #groupName: groupName,
              #members: members,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreActiveGroup({
    required String? groupId,
    required String? role,
    String? inviteCode,
    DateTime? inviteExpiresAt,
    String? groupKey,
    required List<_i6.GroupMember>? members,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreActiveGroup, [], {
              #groupId: groupId,
              #role: role,
              #inviteCode: inviteCode,
              #inviteExpiresAt: inviteExpiresAt,
              #groupKey: groupKey,
              #members: members,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> activateMember(String? groupId, String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#activateMember, [groupId, deviceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> confirmLocalGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmLocalGroup, [groupId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeGroupKey(String? groupId, String? groupKeyBase64) =>
      (super.noSuchMethod(
            Invocation.method(#storeGroupKey, [groupId, groupKeyBase64]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.GroupInfo?> getActiveGroup() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveGroup, []),
            returnValue: _i3.Future<_i7.GroupInfo?>.value(),
          )
          as _i3.Future<_i7.GroupInfo?>);

  @override
  _i3.Stream<_i7.GroupInfo?> watchActiveGroup() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGroup, []),
            returnValue: _i3.Stream<_i7.GroupInfo?>.empty(),
          )
          as _i3.Stream<_i7.GroupInfo?>);

  @override
  _i3.Future<_i7.GroupInfo?> getPendingGroup() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingGroup, []),
            returnValue: _i3.Future<_i7.GroupInfo?>.value(),
          )
          as _i3.Future<_i7.GroupInfo?>);

  @override
  _i3.Future<_i7.GroupInfo?> getGroupById(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupById, [groupId]),
            returnValue: _i3.Future<_i7.GroupInfo?>.value(),
          )
          as _i3.Future<_i7.GroupInfo?>);

  @override
  _i3.Future<void> updateLastSyncTime(DateTime? syncTime) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSyncTime, [syncTime]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMembers(
    String? groupId,
    List<_i6.GroupMember>? members,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMembers, [groupId, members]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateInviteCode(
    String? groupId,
    String? inviteCode,
    DateTime? expiresAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInviteCode, [
              groupId,
              inviteCode,
              expiresAt,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deactivateGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateGroup, [groupId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGroupName(String? groupId, String? groupName) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupName, [groupId, groupName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMemberProfile({
    required String? groupId,
    required String? deviceId,
    required String? displayName,
    required String? avatarEmoji,
    String? avatarImagePath,
    String? avatarImageHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberProfile, [], {
              #groupId: groupId,
              #deviceId: deviceId,
              #displayName: displayName,
              #avatarEmoji: avatarEmoji,
              #avatarImagePath: avatarImagePath,
              #avatarImageHash: avatarImageHash,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
