// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/data/repositories/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:home_pocket/infrastructure/crypto/models/chain_verification_result.dart'
    as _i2;
import 'package:home_pocket/infrastructure/crypto/services/field_encryption_service.dart'
    as _i3;
import 'package:home_pocket/infrastructure/crypto/services/hash_chain_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChainVerificationResult_0 extends _i1.SmartFake
    implements _i2.ChainVerificationResult {
  _FakeChainVerificationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FieldEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFieldEncryptionService extends _i1.Mock
    implements _i3.FieldEncryptionService {
  MockFieldEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> encryptField(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptField,
          [plaintext],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #encryptField,
            [plaintext],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> decryptField(String? ciphertext) => (super.noSuchMethod(
        Invocation.method(
          #decryptField,
          [ciphertext],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #decryptField,
            [ciphertext],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> encryptAmount(double? amount) => (super.noSuchMethod(
        Invocation.method(
          #encryptAmount,
          [amount],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #encryptAmount,
            [amount],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<double> decryptAmount(String? encryptedAmount) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptAmount,
          [encryptedAmount],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [HashChainService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHashChainService extends _i1.Mock implements _i6.HashChainService {
  MockHashChainService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String calculateTransactionHash({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTransactionHash,
          [],
          {
            #transactionId: transactionId,
            #amount: amount,
            #timestamp: timestamp,
            #previousHash: previousHash,
          },
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #calculateTransactionHash,
            [],
            {
              #transactionId: transactionId,
              #amount: amount,
              #timestamp: timestamp,
              #previousHash: previousHash,
            },
          ),
        ),
      ) as String);

  @override
  bool verifyTransactionIntegrity({
    required String? transactionId,
    required double? amount,
    required int? timestamp,
    required String? previousHash,
    required String? currentHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTransactionIntegrity,
          [],
          {
            #transactionId: transactionId,
            #amount: amount,
            #timestamp: timestamp,
            #previousHash: previousHash,
            #currentHash: currentHash,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.ChainVerificationResult verifyChain(
          List<Map<String, dynamic>>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyChain,
          [transactions],
        ),
        returnValue: _FakeChainVerificationResult_0(
          this,
          Invocation.method(
            #verifyChain,
            [transactions],
          ),
        ),
      ) as _i2.ChainVerificationResult);

  @override
  _i2.ChainVerificationResult verifyChainIncremental(
    List<Map<String, dynamic>>? transactions, {
    required int? lastVerifiedIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyChainIncremental,
          [transactions],
          {#lastVerifiedIndex: lastVerifiedIndex},
        ),
        returnValue: _FakeChainVerificationResult_0(
          this,
          Invocation.method(
            #verifyChainIncremental,
            [transactions],
            {#lastVerifiedIndex: lastVerifiedIndex},
          ),
        ),
      ) as _i2.ChainVerificationResult);
}
