// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/features/accounting/application/use_cases/update_transaction_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/features/accounting/domain/models/category.dart'
    as _i6;
import 'package:home_pocket/features/accounting/domain/models/transaction.dart'
    as _i4;
import 'package:home_pocket/features/accounting/domain/repositories/category_repository.dart'
    as _i5;
import 'package:home_pocket/features/accounting/domain/repositories/transaction_repository.dart'
    as _i2;
import 'package:home_pocket/infrastructure/crypto/services/field_encryption_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i4.Transaction? transaction) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.Transaction? transaction) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> softDelete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Transaction?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Transaction?>.value(),
      ) as _i3.Future<_i4.Transaction?>);

  @override
  _i3.Future<List<_i4.Transaction>> findByBook({
    required String? bookId,
    DateTime? startDate,
    DateTime? endDate,
    List<String>? categoryIds,
    _i4.LedgerType? ledgerType,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByBook,
          [],
          {
            #bookId: bookId,
            #startDate: startDate,
            #endDate: endDate,
            #categoryIds: categoryIds,
            #ledgerType: ledgerType,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<String?> getLatestHash(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #getLatestHash,
          [bookId],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<int> count(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [bookId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> verifyHashChain(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #verifyHashChain,
          [bookId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i5.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i6.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i6.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.Category?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i3.Future<_i6.Category?>.value(),
      ) as _i3.Future<_i6.Category?>);

  @override
  _i3.Future<List<_i6.Category>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i3.Future<List<_i6.Category>>);

  @override
  _i3.Future<List<_i6.Category>> findByLevel(int? level) => (super.noSuchMethod(
        Invocation.method(
          #findByLevel,
          [level],
        ),
        returnValue: _i3.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i3.Future<List<_i6.Category>>);

  @override
  _i3.Future<List<_i6.Category>> findByParent(String? parentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByParent,
          [parentId],
        ),
        returnValue: _i3.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i3.Future<List<_i6.Category>>);

  @override
  _i3.Future<List<_i6.Category>> findByType(_i4.TransactionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i3.Future<List<_i6.Category>>);

  @override
  _i3.Future<bool> canDelete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #canDelete,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> seedSystemCategories() => (super.noSuchMethod(
        Invocation.method(
          #seedSystemCategories,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FieldEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFieldEncryptionService extends _i1.Mock
    implements _i7.FieldEncryptionService {
  MockFieldEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> encryptField(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptField,
          [plaintext],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #encryptField,
            [plaintext],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> decryptField(String? ciphertext) => (super.noSuchMethod(
        Invocation.method(
          #decryptField,
          [ciphertext],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #decryptField,
            [ciphertext],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> encryptAmount(double? amount) => (super.noSuchMethod(
        Invocation.method(
          #encryptAmount,
          [amount],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #encryptAmount,
            [amount],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<double> decryptAmount(String? encryptedAmount) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptAmount,
          [encryptedAmount],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
