// Mocks generated by Mockito 5.4.6 from annotations
// in home_pocket/test/unit/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_pocket/infrastructure/crypto/services/field_encryption_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FieldEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFieldEncryptionService extends _i1.Mock
    implements _i2.FieldEncryptionService {
  MockFieldEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> encryptField(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encryptField, [plaintext]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encryptField, [plaintext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> decryptField(String? ciphertext) =>
      (super.noSuchMethod(
            Invocation.method(#decryptField, [ciphertext]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decryptField, [ciphertext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> encryptAmount(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#encryptAmount, [amount]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encryptAmount, [amount]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<double> decryptAmount(String? encrypted) =>
      (super.noSuchMethod(
            Invocation.method(#decryptAmount, [encrypted]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
